LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := QCAR
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
LOCAL_SRC_FILES := prebuilt/$(TARGET_ARCH_ABI)/libQCAR.so

include $(PREBUILT_SHARED_LIBRARY)
